Blog app - Views
muneeb3123/blog-app pull request #6
Opened 2023-08-01 14:21 UTC by muneeb3123

This pr includes:

- Use preprocessed HTML file with embedded Ruby code.

- Use layouts and templates for shared content.

- Implement the design from the sneak peek wireframes.

- Styling is nice to have but focus on making sure everything functions first. (Note: Ignore login logic, you would be using Devise in coming milestone)

2023-08-01 15:34 UTC, BregornOriginal requested changes
Hi @muneeb3123 

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

![hand-sketching-stair-slogan-one-step-closer-chalkboard-79948193](https://github.com/muneeb3123/blog-app/assets/93630700/1a897a5f-7136-4bf9-839c-f3c29a91edd8)

## Highlights

✅ Linters are passing
✅ Good commit history
✅ README looks professional


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 15:34 UTC, BregornOriginal commented on app/controllers/posts_controller.rb
> +  def index
- [ ] To follow the different wireframes, we can see that the home page `http://localhost:3000/` shows a list of users, which means this page is `users#index`. Kindly add this to your `config/routes` to match with the wireframe routes

2023-08-01 15:34 UTC, BregornOriginal commented on app/views/posts/show.html.erb
> +    <div class="single-post-container">
- [ ] Kindly add your styling to this view to match the requirements on the wireframe provided

Your design (without styles)

![image](https://github.com/muneeb3123/blog-app/assets/93630700/cb5244b0-8ca4-4a22-89ba-ca1e698123ce)

Wireframe

![image](https://github.com/muneeb3123/blog-app/assets/93630700/79ab1c1d-a516-46ce-b2cc-af91329af35d)

2023-08-01 15:34 UTC, BregornOriginal commented on app/views/posts/index.html.erb
> +    <div class="posts-main-container">
- [ ] Kindly add your styling to this view to match the requirements on the wireframe provided

Your design (without styles)

![image](https://github.com/muneeb3123/blog-app/assets/93630700/c7c4414f-01be-45b2-98d5-8c7a951a86c7)

Wireframe

![image](https://github.com/muneeb3123/blog-app/assets/93630700/4a86fe08-a962-4720-a3c0-1f8ea4d80fec)

2023-08-01 15:34 UTC, BregornOriginal commented on app/views/users/index.html.erb
> +    <div class="users-container" >
- [ ] Kindly add your styling to this view to match the requirements on the wireframe provided

Your design (without styles)

![image](https://github.com/muneeb3123/blog-app/assets/93630700/8412fd57-bfa4-4911-94ff-1a015cb75d5c)

Wireframe

![image](https://github.com/muneeb3123/blog-app/assets/93630700/63f4936e-dd04-44dc-b1ce-0c935c683888)

2023-08-01 15:34 UTC, BregornOriginal commented on app/views/users/show.html.erb
> +    <div class="single-user-container">
- [ ] Kindly add your styling to this view to match the requirements on the wireframe provided

Your design (without styles)

![image](https://github.com/muneeb3123/blog-app/assets/93630700/c3e079d4-0490-49a9-b06d-74bb009fc981)

Wireframe

![image](https://github.com/muneeb3123/blog-app/assets/93630700/568e14e7-e9a0-4b23-8cbd-80eb403c92d4)

2023-08-02 02:03 UTC, Shedrack-Sunday approved these changes
Hi @muneeb3123   

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Rails  features ✔️ 
- [x] Kudus on meeting the requirements suggested b the last reviewer ✔️


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-08-02 02:06 UTC, merged